## What to Vary

In [1]:
# language="english"
# language="multilingual"
# DeepPavlov/rubert-base-cased-sentence


# raw text or vw text


# default topics (whatever)
# specific number of topics


# KeyBERTInspired
# openchat

In [2]:
from topicnet.cooking_machine import Dataset

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, TextGeneration

from umap import UMAP
from hdbscan import HDBSCAN

from hdbscan.flat import HDBSCAN_flat

from sklearn.feature_extraction.text import CountVectorizer

import gensim.corpora as corpora

from gensim.models.coherencemodel import CoherenceModel

import pandas as pd

In [3]:
import nltk
from nltk.corpus import stopwords
 
nltk.download('stopwords')

print(stopwords.words('russian'))

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/alekseev_v/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
DATA_FOLDER_PATH = '/home/alekseev_v/miniconda3/envs/topicnet/lib/python3.8/site-packages/topicnet/dataset_manager'

In [5]:
! ls $DATA_FOLDER_PATH

20NG.csv	 MKB10__internals	    RTL_Wiki.csv
20NG__internals  postnauka.csv		    RTL_Wiki_person.csv
api.py		 postnauka__internals	    RTL_Wiki_person__internals
Brown		 postnauka_noow.csv	    ruwiki_good__internals
Brown_BOW.csv	 postnauka_noow__internals  ruwiki_good.txt
Brown_NOOW.csv	 __pycache__		    WikiRef-220
hf		 Reuters		    wiki_ref220_bow.csv
__init__.py	 Reuters_BOW.csv	    wiki_ref220_natural_order.csv
MKB10.csv	 Reuters_NOOW.csv

In [6]:
dataset = Dataset(
    f'{DATA_FOLDER_PATH}/ruwiki_good.txt',
)

dataset.get_possible_modalities()

{'@categories', '@lemmatized', '@ngramms'}

In [7]:
MAIN_MODALITY = '@lemmatized'

In [8]:
dataset._data.head()

,vw_text,raw_text,id
id,,,
Санкт-Петербург,Санкт-Петербург |@lemmatized год:301 петроград...,,Санкт-Петербург
Дворцовая_площадь,Дворцовая_площадь |@lemmatized дворцовый:43 пл...,,Дворцовая_площадь
Греко-персидские_войны,Греко-персидские_войны |@lemmatized грёкий:23 ...,,Греко-персидские_войны
Тихий_океан,Тихий_океан |@lemmatized тихий:92 океан:174 ус...,,Тихий_океан
Атлантический_океан,Атлантический_океан |@lemmatized атлантический...,,Атлантический_океан

In [9]:
dataset._data['raw_text']

id
Санкт-Петербург
Дворцовая_площадь
Греко-персидские_войны
Тихий_океан
Атлантический_океан
                                      ..
Бассет,_Филипп
Битва_при_Линкольне_(1217)
Лю_Жэньхан
Реформа_эталонных_процентных_ставок
Ментеше-бей
Name: raw_text, Length: 8603, dtype: object

In [10]:
dataset._data.shape

(8603, 3)

In [11]:
dataset._data.dropna(axis=0, inplace=True)

In [12]:
dataset._data.shape

(8603, 3)

In [13]:
dataset._data['vw_text']

id
Санкт-Петербург                        Санкт-Петербург |@lemmatized год:301 петроград...
Дворцовая_площадь                      Дворцовая_площадь |@lemmatized дворцовый:43 пл...
Греко-персидские_войны                 Греко-персидские_войны |@lemmatized грёкий:23 ...
Тихий_океан                            Тихий_океан |@lemmatized тихий:92 океан:174 ус...
Атлантический_океан                    Атлантический_океан |@lemmatized атлантический...
                                                             ...
Бассет,_Филипп                         Бассет,_Филипп |@lemmatized бассет:44 <person>...
Битва_при_Линкольне_(1217)             Битва_при_Линкольне_(1217) |@lemmatized битва:...
Лю_Жэньхан                             Лю_Жэньхан |@lemmatized лю:29 жэньхан:25 китай...
Реформа_эталонных_процентных_ставок    Реформа_эталонных_процентных_ставок |@lemmatiz...
Ментеше-бей                            Ментеше-бей |@lemmatized ?:1 умереть:2 основат...
Name: vw_text, Length: 8603, dtype: object

In [14]:
dataset._data['vw_text'][0]

'Санкт-Петербург |@lemmatized год:301 петроград:7 ленинград:18 численность:14 население:33 город:212 россия:32 .:677 федеральный:15 значение:8 административный:5 центр:29 округа:3 ленинградский:16 область:6 основать:5 царь:3 <person>:195 являться:34 столица:19 российский:35 государство:9 назвать:4 честь:6 святой:11 небесный:2 покровитель:2 основатель:3 время:17 стать:25 большой:23 ассоциироваться:1 имя:34 исторически:1 культурно:1 связать:2 рождение:1 империя:7 вхождение:1 современный:7 история:11 роль:5 европейский:3 великий:5 держава:1 расположить:11 страна:16 побережье:4 финский:16 залив:15 устье:4 река:21 нева:31 находиться:17 конституционный:1 суд:5 федерация:14 геральдический:2 совет:8 президент:1 орган:6 власть:11 межпарламентский:3 ассамблея:3 снг:2 разместить:1 главный:9 командование:2 флот:1 штаб:2 западный:8 военный:8 вооружённый:3 сила:6 быть:74 революция:6 февральский:2 октябрьский:6 ход:4 отечественный:4 война:10 блокада:7 результат:12 миллион:37 человек:39 погибнуть:4 объявить:1 герой:4 состояние:9 состав:8 воинский:2 слава:1 кронштадт:3 колпино:3 чело:2 северный:15 мир:10 миллионник:1 полностью:6 европа:12 житель:17 инновационный:1 сценарий:1 стратегия:2 развитие:15 предполагать:1 что:10 составить:27 городской:20 агломерация:2 площадь:29 расширение:2 москва:11 второе:3 важный:8 экономический:10 научный:6 культурный:12 крупный:26 транспортный:7 узел:4 исторический:8 связанный:6 комплекс:6 памятник:15 входить:2 список:5 объект:10 всемирный:3 наследие:8 юнеско:3 туризм:3 наиболее:5 значимый:1 эрмитаж:2 кунсткамера:3 мариинский:5 театр:14 национальный:8 библиотека:5 русский:18 музей:14 петропавловский:11 крепость:12 исаакиевский:6 собор:26 проспект:24 сохранение:3 направить:1 программа:3 посетить:3 турист:7 предел:2 приневский:1 низменность:1 координата:1 занимать:5 прилегать:1 невский:18 губа:9 многочисленный:4 остров:29 дельта:6 протянуться:1 километр:5 высота:7 уровень:10 море:5 район:16 север:3 юг:5 высокий:14 место:22 черта:5 дудергофский:2 красный:3 село:3 максимальный:1 территория:22 нулевой:2 отметка:2 система:8 отсчёт:2 глубина:1 служащий:2 исходный:1 пункт:2 нивелирный:1 сеть:8 начало:12 xx:6 век:26 проходить:7 обсерватория:4 меридиан:1 использоваться:2 качество:6 географический:3 долгота:1 карта:1 протяжённость:3 водоток:1 достигать:1 водный:9 поверхность:5 составлять:22 существование:2 гидрологический:1 претерпеть:1 существенный:3 изменение:3 строительство:13 низок:1 болотистый:1 потребовать:1 сооружение:12 канал:18 пруд:1 осушение:1 вынуть:1 земля:5 повышение:2 конец:4 xix:5 состоять:3 образующая:1 мера:4 многие:8 водоём:2 терять:1 первоначальный:5 загрязняться:1 засыпаться:1 засыпка:1 проток:1 рукав:3 сократиться:2 основный:8 магистраль:3 впадать:1 относиться:2 балтийский:11 значительный:11 малый:4 средний:6 невки:2 фонтанка:3 мойка:2 екатерингофка:1 крестовка:1 карповка:1 ждановка:1 пряжка:1 кронверкский:1 пролив:1 морской:19 обводный:1 основной:4 приток:2 слева:2 ижора:2 славянка:1 мурзинка:1 справа:2 охт:2 чёрный:2 речка:1 васильевский:12 петроградский:3 крестовский:5 декабрист:1 котлин:2 перекинуть:1 мост:11 считать:5 промышленный:10 предприятие:19 пешеходный:1 разводный:1 количество:10 часть:18 некогда:1 пригород:4 пушкин:3 петергоф:5 павловск:2 длинный:2 обуховский:3 вантовый:2 полный:3 длина:2 мостовый:1 переход:1 широкий:3 синий:1 полоса:1 линия:4 железный:8 дорога:12 левобережье:1 превышать:4 подверженный:1 опасность:2 наводнение:14 главное:3 образ:5 ветровый:1 нагон:1 вод:13 восточный:4 катастрофический:1 характер:2 носить:1 подъесть:1 выше:4 ординар:3 затопить:1 трехсотлетний:1 петербург:30 зарегистрировать:7 разный:3 источник:7 опасный:2 подняться:5 сантиметр:5 кронштадтский:3 футшток:1 вступить:5 строить:5 защитный:1 дамба:4 впервые:4 задействовать:1 закрыть:1 прогноз:1 специалист:1 пятёрка:1 величина:5 наблюдение:2 вода:9 мочь:6 уйти:4 предотвратить:1 ущерб:2 миллиард:7 рубль:15 климат:3 умеренный:1 переходный:1 умеренно:2 континентальный:2 тип:1 объясняться:1 положение:1 атмосферный:2 циркуляция:1 характерный:4 обусловливаться:1 сравнительно:1 небольшой:2 поступать:1 земной:1 атмосфера:2 солнечный:6 тепло:2 классификация:1 кеппена:1 классифицироваться:1 как:23 влажный:2 влияние:1 циклон:1 давать:4 жаркое:1 короткий:1 лето:1 холодный:1 сырой:1 зима:1 суммарный:4 радиация:5 маленький:3 украина:1 вдвое:1 азия:1 бывать:1 среднее:5 протяжение:2 преобладать:6 облачный:1 пасмурный:1 погода:1 рассеянный:1 освещение:1 продолжительность:3 меняться:1 часы:2 минута:3 наблюдаться:4 называть:4 белые:1 ночь:5 наступать:1 заканчиваться:1 когда:2 солнце:1 опускаться:1 горизонт:1 вечерний:2 сумерки:1 практически:3 сливаться:1 утренний:1 сложность:1 годовой:2 амплитуда:1 сумма:2 прямая:4 горизонтальный:1 ясный:1 небо:1 мдж:3 облачность:1 уменьшать:1 приход:1 среднегодовой:1 частый:1 смена:3 воздушный:2 масса:1 обусловить:1 степень:1 циклонический:1 деятельность:3 летом:2 ветер:1 зимой:1 петербургский:18 метеостанция:1 располагать:1 дать:3 температура:1 период:5 низкий:2 зелёный:2 насаждение:3 приходиться:4 тысяча:53 га:1 парковый:4 сад:4 сквер:1 бульвар:1 озеленить:1 улица:11 парка:5 различный:5 ландшафтный:1 условие:4 нижний:1 верхний:1 терраса:1 стрельна:2 моренный:1 равнина:1 холм:1 шуваловский:1 парк:5 осиновый:1 роща:1 основа:5 ряд:7 естественный:2 леса:1 пора:1 сохранить:1 породный:1 сосновка:1 удельный:2 создать:8 послевоенный:1 разбитый:1 где:6 древесный:1 растительность:1 фактически:1 отсутствовать:1 московский:15 победа:3 приморский:5 окраина:6 сохраниться:3 лесной:6 массив:1 остаться:3 подзона:1 южный:7 тайга:1 юнтоловский:2 дача:1 ржевский:1 лесопарк:1 островок:1 вдоль:2 охта:3 таллинский:2 шоссе:12 дорогой:1 существовать:2 семь:2 особо:2 охранять:2 природный:4 государственный:32 заказник:2 природа:2 комаровский:1 берег:3 стрельнинский:1 сергиевка:1 генеральный:10 план:11 планироваться:2 появление:3 министерство:4 ресурс:1 экология:1 экологический:2 рейтинг:6 занять:3 действовать:17 автоматический:1 станция:12 мониторинг:1 воздух:1 выброс:5 тонна:8 вредный:2 вещество:2 душить:2 килограмм:1 единица:3 транспорт:9 сравнение:2 предыдущий:4 увеличиться:1 стационарный:2 неудовлетворительный:2 загрязнить:1 сток:1 нея:2 сливать:1 отход:5 сотня:1 активно:2 транспортироваться:1 нефтепродукт:3 ежегодно:1 попадать:1 загрязнять:1 комитет:4 природопользование:1 фиксировать:1 акватория:2 разлив:1 роспотребнадзор:1 пляж:1 признать:2 пригодный:1 купание:1 образоваться:2 твёрдый:1 бытовой:2 промышленность:7 разнообразный:2 производство:6 представлять:1 серьёзный:1 окружающий:1 iii:1 класс:1 свозиться:1 утилизация:1 токсичный:1 продукт:6 химический:4 медицинский:4 полигон:1 бора:1 тосненский:1 ввод:2 защита:4 произойти:4 уменьшение:1 водообмен:1 частью:2 дополнительный:3 вклад:2 увеличение:1 концентрация:1 биоген:1 совокупность:2 неудачный:2 выбор:3 очистный:5 загрязнённость:1 грунт:2 некоторый:7 беспокойство:1 вызывать:1 начаться:10 постепенный:1 заболачивание:1 мелководный:1 гниение:1 остаток:1 растение:1 привести:2 эвтрофикация:1 исключение:2 обширный:3 участок:2 захоронить:1 соединение:1 пребывание:1 прослеживаться:1 таяние:1 ледник:1 покрывать:1 примерно:1 лёд:2 отступить:1 вслед:1 прислать:1 сведение:1 славянин:1 ильменский:1 словено:1 кривич:1 известный:4 viii:2 ix:2 заниматься:2 подсечный:1 земледелие:1 скотоводство:1 охота:1 рыбалка:1 совершать:1 набег:1 народ:1 войти:4 древнерусский:1 великое:5 новгород:1 название:23 водскай:1 пятина:1 местность:1 именоваться:1 карельский:1 ижорский:4 xiii:1 путь:5 варяг:1 грек:1 скандинавия:2 византия:1 новгородский:4 республика:4 постоянно:2 вести:1 швед:2 впадение:2 состояться:3 сражение:1 ополчение:1 князь:1 шведский:3 войско:2 построить:17 ландскрон:2 спустя:1 взять:2 объединить:1 дружина:1 новгородец:1 местный:2 карел:1 срыть:1 основание:4 бывший:3 долгий:2 торжище:1 есть:3 рынок:6 xv:1 присоединить:1 княжество:1 поражение:1 швеция:4 столбовский:1 ингерманландия:1 торговый:4 ниена:2 ниеншанца:1 долина:1 отвоевать:1 ништадтский:1 мирный:1 договор:1 неподалёку:1 заложить:2 днём:1 датироваться:1 закладка:1 первое:7 заячий:2 огонь:2 орудие:2 перекрывать:1 фарватер:1 рубеж:1 новый:14 придавать:1 стратегический:1 обеспечение:1 четверть:2 xviii:9 писаться:1 сан:4 бурх:3 специальный:4 акт:2 определять:3 письмо:2 официальный:7 газета:6 ведомость:5 упоминаться:3 соответствие:5 голландский:3 вариант:6 написание:3 зафиксировать:1 десять:1 гостиный:2 двор:6 троицкий:1 церковь:12 множество:2 служебный:1 здание:29 ремесленный:1 слобода:2 адмиралтейский:6 верфь:5 открытый:8 сторона:8 левый:1 дальнейший:3 галерный:1 зимний:6 летний:3 дворец:31 провозгласить:1 лицо:3 царский:6 селиться:1 немой:4 переехать:2 правительствующий:1 сенат:3 указ:9 создаваться:3 инженерный:3 артиллерийский:3 школа:5 издать:3 создание:4 начать:8 застраиваться:2 выборгский:5 развернуть:1 пригородный:1 екатерингоф:1 госпиталь:2 смольный:8 литейный:4 водяной:1 пильный:1 мельница:2 кирпичный:1 восковыя:1 пороховой:2 оружейный:1 шпалерный:1 кожевенный:1 завод:20 пищевой:4 перевести:1 монетный:1 академия:17 наука:7 выходить:1 пожар:3 середина:10 петровский:3 ветхий:2 уничтожить:2 выгореть:1 деревянный:1 императрица:1 комиссия:4 строение:4 возглавлять:2 еропкина:1 утверждаться:1 идея:2 трехлучевой:1 адмиралтейство:7 становиться:3 композиционный:1 отводиться:1 целый:2 учебный:7 заведение:8 институт:13 благородный:1 девица:1 императорский:2 художество:3 горный:2 училище:7 народный:3 подготовка:1 учитель:1 пришлый:1 каменный:2 регулировать:1 застройка:8 набережная:4 малое:4 формирование:3 архитектурный:8 ансамбль:8 центральный:9 гранитный:1 обогнать:1 православный:5 иноверческий:1 насчитываться:2 переулок:1 дом:20 замостить:1 булыжник:1 покрыть:2 поперечный:1 доска:1 заведовать:1 всесословный:2 путём:1 дума:2 корпус:4 инженер:2 сообщение:4 родить:2 образование:9 царскосельский:2 лицей:2 разрушительный:1 подсчёт:1 материальный:1 оцениваться:1 многий:1 сенатский:3 совершить:1 попытка:2 переворот:1 цель:1 упразднение:1 самодержавие:1 половина:3 закончить:3 оформление:1 дворцовый:4 александринский:4 михайловский:6 стрелка:4 трудиться:1 реконструкция:3 синод:2 дж:3 кваренга:2 проект:4 де:2 томон:2 биржа:6 ростральный:1 колонна:2 казанский:5 казначейство:1 монферран:2 александровский:4 фабрика:3 банк:5 столетие:1 путиловский:1 расти:3 индустриальный:2 жилой:3 нарвский:1 застава:1 формироваться:4 плотный:1 многоэтажный:1 доходный:5 пустить:1 паровой:2 машина:4 спустить:2 пароход:1 чугунолитейный:1 выпуск:2 подвижный:1 выпустить:1 паровоз:1 событие:7 поезд:3 вскоре:2 регулярный:1 вокзал:9 николаевский:1 варшавский:1 финляндский:3 завершить:1 постройка:2 километровый:1 порт:10 гутуевский:1 водоснабжение:3 прокладываться:1 водопровод:1 появиться:4 телефонный:2 аппарат:1 поздний:5 трамвай:2 открыться:2 пулковский:5 общество:2 свыше:5 двадцать:1 перепись:3 мировой:6 превысить:2 лондон:2 париж:2 считаться:1 кровавый:1 воскресение:1 парламент:1 объесть:7 достигнуть:1 занятый:1 продукция:7 электрический:2 изделие:6 текстиль:1 энергооснащённость:1 столичный:2 индустрия:2 обеспечивать:3 электроустановка:1 тэц:10 обучаться:1 студент:1 сильно:1 повлиять:1 судьба:1 волна:1 антигерманский:1 настроение:1 ii:5 переименовать:3 измениться:1 смысл:1 называться:3 проблема:1 снабжение:1 обычный:1 явление:2 очередь:3 волнение:1 завершиться:1 отречение:1 император:4 падение:1 монархия:1 временной:1 правительство:7 социалистический:1 перейти:1 рука:1 большевик:1 советский:5 гражданский:2 близость:1 фронт:3 германский:1 армия:1 лишиться:1 статус:3 смерть:2 всесоюзный:2 съезд:4 ссср:5 удовлетворить:2 просьба:2 петросовет:2 постановление:3 революционный:1 рабочий:1 переселить:1 урегулирование:1 начинаться:4 жилищный:3 жилмассив:2 благоустроить:1 выход:2 оконечность:2 стадион:7 киров:6 рсфср:7 выделить:1 отдельный:1 республиканский:1 подчинение:1 разработать:2 предусматривать:2 направление:2 граница:1 пересечение:1 международный:21 дуговой:1 утвердить:3 квартал:2 ивановский:1 культура:12 иметься:5 аэропорт:4 пулково:5 жертва:2 убийство:1 секретарь:1 обком:1 горком:1 вкп:2 член:1 политбюро:1 цк:1 положить:2 кировский:3 поток:1 террор:1 приходить:1 героизм:1 стойкость:1 ленинградец:5 проявиться:1 противник:1 выйти:2 ладожский:3 озеро:2 захватить:1 шлиссельбург:1 контроль:2 исток:1 блокировать:1 суши:1 гитлеровский:1 германия:3 финляндия:3 удержать:1 оказать:2 огромный:2 помощь:2 нюрнбергский:1 процесс:2 фигурировать:1 бомбёжка:1 артобстрел:1 остальной:2 умереть:1 голод:2 энциклопедия:1 свет:2 издательство:1 оборона:2 рф:7 цифра:1 существенно:1 занизить:1 поскольку:2 учесть:1 неопознанный:1 блокадник:1 погибший:1 умерший:1 эвакуация:1 встречный:1 наступление:1 волховский:1 блокадный:1 кольцо:1 прорвать:1 снятой:1 снятие:1 восстановление:1 концертный:4 сезон:2 зал:3 филармония:1 предлагаться:1 развивать:1 приблизительно:1 равный:2 новое:6 калинин:2 комсомольский:1 облик:3 обрести:1 стачка:2 среднеохтинский:1 запустить:1 аэровокзал:1 сдать:1 эксплуатация:5 метрополитен:6 возобновить:2 традиция:2 полуденный:2 выстрел:2 пушка:1 нарышкина:2 бастион:2 прервать:1 марсовый:1 зажечь:1 вечный:2 судостроительный:3 атомный:2 ледокол:2 трактор:2 кировец:1 мемориал:1 пискаревский:1 кладбище:2 аптекарский:1 возвести:1 метровый:1 телебашня:1 телецентр:1 домостроительный:1 комбинат:2 массовый:5 хрущёвка:2 корабль:3 присвоить:1 звание:1 приказ:1 верховный:3 главнокомандующий:1 одобрить:1 намывной:1 новоизмайловский:1 гагарин:1 космонавт:1 купчиный:1 автовый:2 дачный:1 гражданка:1 полюстровый:2 юбилей:2 спорт:7 юбилейный:3 урицк:1 сосновый:1 поляна:1 весёлый:1 посёлок:1 муринский:1 ручей:1 комендантский:1 аэродром:1 купчина:1 шуваловый:1 озерко:1 ржевка:1 защитить:1 гавань:2 родиться:1 внести:4 референдум:1 горожанин:3 высказаться:2 возвращение:3 президиум:2 возвратить:3 конституция:3 депутат:4 всенародный:1 голосование:2 подтвердить:2 наименование:5 собчак:2 избранный:3 мэр:3 исполнительный:5 передать:1 администрация:3 губернатор:6 должность:1 упразднить:1 игра:2 воля:2 авария:1 мужество:1 прекратить:1 движение:1 установить:1 отреставрировать:1 восстановить:1 константиновский:2 храм:4 спас:2 кровь:3 перерыв:1 церковный:1 служба:2 пройти:2 ледовый:2 чемпионат:2 хоккей:1 кольцевой:2 автомобильный:6 пышно:1 отпраздновать:1 законодательный:6 собрание:5 определить:2 будущее:1 проводиться:4 ежегодный:1 саммит:2 форум:2 политический:3 мероприятие:2 получить:6 неофициальный:5 давос:1 поменять:1 формат:1 руководитель:2 иностранный:3 компания:6 глава:2 лидер:1 председатель:2 министр:1 восьмёрка:1 назначить:1 беглов:2 временно:1 исполнять:1 обязанность:1 футбольный:1 матч:4 групповой:2 этап:2 финал:2 кубок:1 конфедерация:1 фифа:1 футбол:1 сыграть:3 полуфинал:1 третье:1 провести:2 нидерландский:1 форма:4 тпитербурхъ:1 апостол:2 первоначально:1 распространиться:1 устанавливать:1 иноязычный:1 окружение:1 использовать:3 немецкий:2 английский:1 язык:2 равно:1 сподвижник:1 владеть:1 разнобой:2 именование:1 касаться:1 компонент:1 санкт:1 сант:1 нередко:1 родительный:1 падеж:1 питер:1 бурк:1 топоним:5 записать:1 слово:2 встречаться:3 следующий:2 санктъпетерсъбурк:1 сантпитербурх:1 питербурх:2 санктпетерзбурк:1 санктъ:1 санктпитербурх:1 xii:1 сантъпитербург:1 санктпитерзбурк:1 санктъпетерзбурк:1 vi:1 чаща:1 санктъпитербурх:1 начинать:2 вместо:2 позволять:1 широко:1 употребляться:2 настоящее:1 распространение:2 установиться:1 чисто:1 употребление:2 просторечие:1 инициатива:1 организатор:1 скончаться:1 опрос:4 участвовать:2 продолжать:2 ст:1 поправка:1 опубликование:1 инициатор:1 решающий:2 впоследствии:2 достижение:1 увековечить:1 установленный:2 надеяться:1 банковский:1 туристический:3 балтика:2 оптимизм:1 оценивать:1 возможность:1 перенос:1 xxi:1 старший:4 поколение:1 молодёжь:1 коммунистический:1 просоветский:1 взгляд:1 группа:4 прежний:2 организация:9 зоопарк:2 ленэнерго:1 астероид:1 петрополитать:1 астроном:1 симеизский:1 зависимость:1 петроградец:2 петроградка:1 ленинградка:1 петербуржец:5 петербуржка:1 санктпетербуржец:2 питерец:2 идентифицировать:1 понятие:1 опросить:1 осуществляться:3 устав:3 должностной:1 избирать:2 гражданин:2 проживать:3 обладать:3 закон:2 активный:3 избирательный:2 право:3 всеобщий:1 прямой:1 тайный:1 срок:2 осуществлять:4 иной:3 размещаться:2 пропорциональный:1 сформировать:2 созыв:1 присутствовать:1 фракция:1 единый:1 справедливый:1 кпрф:1 лдпр:1 партия:1 рост:3 яблоко:1 осуществление:1 исполнение:2 бюджет:2 расходование:1 средство:2 внебюджетный:1 фонд:1 контрольный:1 счётный:1 палата:1 судебный:1 уставный:1 судья:1 муниципальный:2 налог:3 прибыль:1 доход:2 физический:3 акциз:1 имущество:2 использование:2 собственность:3 статья:3 расход:2 экономика:4 здравоохранение:9 социальный:1 политика:2 хозяйство:4 общегосударственный:1 вопрос:1 кинематография:1 долг:1 иметь:3 внешний:1 периодически:1 побратим:1 консульство:3 почётный:2 представительство:4 участник:1 банка:2 филиал:2 евразийский:3 сообщество:1 субъект:2 автономия:1 объединение:7 землячество:1 герб:3 дополнить:1 отменяться:1 вновь:1 ввести:4 старый:4 символ:8 флаг:3 регистр:1 присвоение:1 регистрационный:1 номер:2 изобразить:1 скипетр:1 якорь:2 речной:5 прообраз:1 послужить:1 ватикан:1 обозначать:1 конституционно:1 правовой:1 единство:2 достояние:1 девять:1 месяц:2 соответствующий:1 решение:2 гимн:2 музыка:1 балет:5 медный:4 всадник:4 глиэра:1 редакция:1 корчмара:1 согласно:3 кораблик:1 шпиль:2 ангел:1 пушечный:1 сигнальный:1 помимо:3 общероссийский:1 праздник:3 отмечаться:3 памятный:1 дата:2 <tag>:3 стамбул:1 миллионер:1 устойчивый:1 депопуляция:1 прирост:3 счёт:1 превышение:1 миграционный:1 убыль:1 итог:3 росстат:2 показатель:7 рождаемость:1 смертность:2 всероссийский:3 мужчина:3 женщина:3 ожидать:1 жизнь:4 пенсионер:1 инвалид:1 возраст:1 представитель:2 национальность:2 народность:2 указать:1 украинец:1 белорус:1 татарин:1 еврей:1 узбек:1 армянин:1 азербайджанец:1 таджик:1 грузин:1 молдаванин:1 казах:1 финн:1 неоконченный:1 неграмотный:1 регистрировать:1 безработица:1 экономически:1 номинальный:1 заработный:2 плат:2 начислить:1 прожиточный:1 минимум:1 расчёт:1 валовый:2 региональный:6 врп:2 триллион:3 вид:5 скобка:1 доля:9 финансовый:2 валютный:1 товарный:2 пао:2 сырьевой:1 втб:1 таврический:2 балтинвестбанк:1 регион:2 оценка:2 mercer:1 привлечь:1 порядок:2 стадия:1 реализация:3 инвестиционный:1 отгрузить:2 структура:3 оборудование:8 включая:2 напиток:3 табак:1 металлургия:2 готовый:1 металлический:2 тяжёлый:1 работать:9 вмф:3 танкер:1 подводный:1 лодка:1 средне:1 катер:1 тральщик:1 морфлот:2 машиностроение:2 компрессор:1 компрессорный:2 нефтегазовый:1 газовый:1 гидравлический:1 турбина:1 электросила:1 электромашина:1 генератор:1 электропульт:1 аппаратура:2 севкабель:1 силовой:1 кабель:1 прокат:1 металлопродукция:1 сельскохозяйственный:1 техника:1 арсенал:1 космический:1 спутник:1 установка:1 прокатный:1 реактор:1 ленинец:1 авиация:1 вооружение:2 радиоэлектронный:2 рентгеновский:1 трубка:1 комплектовать:1 оптический:1 прибор:1 развитый:4 вагонмаш:1 пассажирский:8 вагон:1 электровагон:1 ford:1 toyota:1 general:1 motors:1 scania:1 nissan:1 hyundai:1 motor:1 man:1 собрать:1 автомобиль:1 продавать:1 отрасль:2 трубный:1 северсталь:1 цветной:1 выборжец:1 вмп:1 лёгкий:1 полиграфический:1 пивоваренный:2 пиво:1 безалкогольный:1 минеральный:2 пивзавод:1 heineken:1 хлебозавод:1 хлебобулочный:1 мучнистый:1 кондитерский:2 принадлежать:3 fazer:1 конфета:1 шоколад:1 мясокомбинат:2 парнас:1 колбасный:1 мясной:1 консервы:1 полуфабрикат:1 круп:1 мука:1 молочный:1 петмол:1 danone:1 рыбный:1 работник:3 оперативный:1 статистический:1 отчётность:1 среднемесячный:1 оборот:4 розничный:3 торговля:5 табачный:1 непродовольственный:1 товар:2 платный:1 услуга:1 потребительский:1 работа:6 занятой:2 внутренний:4 включать:4 продовольственный:1 повседневный:1 спрос:1 реализовать:1 общественный:4 питание:1 обслуживание:3 мелкорозничный:1 специализировать:1 сельхозпродукция:1 представить:3 ашан:1 руока:1 spar:1 metro:1 prisma:1 кей:1 лента:1 дикси:1 магнит:1 пятёрочка:1 карусель:1 перекрёсток:1 принадлежащий:1 retail:1 group:1 межрегиональный:1 семья:1 верный:1 норма:1 нетто:1 азбука:1 вкус:2 полушка:1 лайм:1 лэнд:1 риома

In [15]:
import re

def get_modality_tokens(text, modality):
    m = re.search(fr'\|{modality} ([^@]+) \|@', text)
    vw_text = m.groups()[0]

    text = ''

    for token_freq in vw_text.split():
        token, freq = token_freq.split(':')

        if freq == '':
            freq = 1
        else:
            freq = int(freq)

        text += (token + ' ') * freq

    return text.strip()

In [16]:
get_modality_tokens(dataset._data['vw_text'][0], MAIN_MODALITY)

'год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год петроград петроград петроград петроград петроград петроград петроград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград численность численность численность численность численность численность численность численность численность численность численность численность численность численность население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный значение значение значение значение значение значение значение значение административный административный административный административный административный центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр округа округа округа ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский область область область область область область основать основать основать основать основать царь царь царь <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский государство государство государство государство государство государство государство государство государство назвать назвать назвать назвать честь честь честь честь честь честь святой святой святой святой святой святой святой святой святой святой святой небесный небесный покровитель покровитель основатель основатель основатель время время время время время время время время время время время время время время время время время стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой ассоциироваться имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя исторически культурно связать связать рождение империя империя империя империя империя империя империя вхождение современный современный современный современный современный современный современный история история история история история история история история история история история роль роль роль роль роль европейский европейский европейский великий великий великий великий великий держава расположить расположить расположить расположить расположить расположить расположить расположить расположить расположить расположить страна страна страна страна страна страна страна страна страна страна страна страна страна страна страна страна побережье побережье побережье побережье финский финский финский финский финский финский финский финский финский финский финский финский финский финский финский финский залив залив залив залив залив залив залив залив залив залив залив залив залив залив залив устье устье устье устье река река река река река река река река река река река река река река река река река река река река река нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться конституционный суд суд суд суд суд федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация геральдический геральдический совет совет совет совет совет совет совет совет президент орган орган орган орган орган орган власть власть власть власть власть власть власть власть власть власть власть межпарламентский межпарламентский межпарламентский ассамблея ассамблея ассамблея снг снг разместить главный главный главный главный главный главный главный главный главный командование командование флот штаб штаб западный западный западный западный западный западный западный западный военный военный военный военный военный военный военный военный вооружённый вооружённый вооружённый сила сила сила сила сила сила быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть революция революция революция революция революция революция февральский февральский октябрьский октябрьский октябрьский октябрьский октябрьский октябрьский ход ход ход ход отечественный отечественный отечественный отечественный война война война война война война война война война война блокада блокада блокада блокада блокада блокада блокада результат результат результат результат результат результат результат результат результат результат результат результат миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек погибнуть погибнуть погибнуть погибнуть объявить герой герой герой герой состояние состояние состояние состояние состояние состояние состояние состояние состояние состав состав состав состав состав состав состав состав воинский воинский слава кронштадт кронштадт кронштадт колпино колпино колпино чело чело северный северный северный северный северный северный северный северный северный северный северный северный северный северный северный мир мир мир мир мир мир мир мир мир мир миллионник полностью полностью полностью полностью полностью полностью европа европа европа европа европа европа европа европа европа европа европа европа житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель инновационный сценарий стратегия стратегия развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие предполагать что что что что что что что что что что составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской агломерация агломерация площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь расширение расширение москва москва москва москва москва москва москва москва москва москва москва второе второе второе важный важный важный важный важный важный важный важный экономический экономический экономический экономический экономический экономический экономический экономический экономический экономический научный научный научный научный научный научный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный транспортный транспортный транспортный транспортный транспортный транспортный транспортный узел узел узел узел исторический исторический исторический исторический исторический исторический исторический исторический связанный связанный связанный связанный связанный связанный комплекс комплекс комплекс комплекс комплекс комплекс памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник входить входить список список список список список объект объект объект объект объект объект объект объект объект объект всемирный всемирный всемирный наследие наследие наследие наследие наследие наследие наследие наследие юнеско юнеско юнеско туризм туризм туризм наиболее наиболее наиболее наиболее наиболее значимый эрмитаж эрмитаж кунсткамера кунсткамера кунсткамера мариинский мариинский мариинский мариинский мариинский театр театр театр театр театр театр театр театр театр театр театр театр театр театр национальный национальный национальный национальный национальный национальный национальный национальный библиотека библиотека библиотека библиотека библиотека русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский музей музей музей музей музей музей музей музей музей музей музей музей музей музей петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость исаакиевский исаакиевский исаакиевский исаакиевский исаакиевский исаакиевский собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект сохранение сохранение сохранение направить программа программа программа посетить посетить посетить турист турист турист турист турист турист турист предел предел приневский низменность координата занимать занимать занимать занимать занимать прилегать невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский губа губа губа губа губа губа губа губа губа многочисленный многочисленный многочисленный многочисленный остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров дельта дельта дельта дельта дельта дельта протянуться километр километр километр километр километр высота высота высота высота высота высота высота уровень уровень уровень уровень уровень уровень уровень уровень уровень уровень море море море море море район район район район район район район район район район район район район район район район север север север юг юг юг юг юг высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий место место место место место место место место место место место место место место место место место место место место место место черта черта черта черта черта дудергофский дудергофский красный красный красный село село село максимальный территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория нулевой нулевой отметка отметка система система система система система система система система отсчёт отсчёт глубина служащий служащий исходный пункт пункт нивелирный сеть сеть сеть сеть сеть сеть сеть сеть начало начало начало начало начало начало начало начало начало начало начало начало xx xx xx xx xx xx век век век век век век век век век век век век век век век век век век век век век век век век век век проходить проходить проходить проходить проходить проходить проходить обсерватория обсерватория обсерватория обсерватория меридиан использоваться использоваться качество качество качество качество качество качество географический географический географический долгота карта протяжённость протяжённость протяжённость водоток достигать водный водный водный водный водный водный водный водный водный поверхность поверхность поверхность поверхность поверхность составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять с

In [17]:
get_modality_tokens(dataset._data['vw_text'][0], MAIN_MODALITY)

'год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год петроград петроград петроград петроград петроград петроград петроград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград численность численность численность численность численность численность численность численность численность численность численность численность численность численность население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный значение значение значение значение значение значение значение значение административный административный административный административный административный центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр округа округа округа ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский область область область область область область основать основать основать основать основать царь царь царь <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский государство государство государство государство государство государство государство государство государство назвать назвать назвать назвать честь честь честь честь честь честь святой святой святой святой святой святой святой святой святой святой святой небесный небесный покровитель покровитель основатель основатель основатель время время время время время время время время время время время время время время время время время стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой ассоциироваться имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя исторически культурно связать связать рождение империя империя империя империя империя империя империя вхождение современный современный современный современный современный современный современный история история история история история история история история история история история роль роль роль роль роль европейский европейский европейский великий великий великий великий великий держава расположить расположить расположить расположить расположить расположить расположить расположить расположить расположить расположить страна страна страна страна страна страна страна страна страна страна страна страна страна страна страна страна побережье побережье побережье побережье финский финский финский финский финский финский финский финский финский финский финский финский финский финский финский финский залив залив залив залив залив залив залив залив залив залив залив залив залив залив залив устье устье устье устье река река река река река река река река река река река река река река река река река река река река река нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться конституционный суд суд суд суд суд федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация геральдический геральдический совет совет совет совет совет совет совет совет президент орган орган орган орган орган орган власть власть власть власть власть власть власть власть власть власть власть межпарламентский межпарламентский межпарламентский ассамблея ассамблея ассамблея снг снг разместить главный главный главный главный главный главный главный главный главный командование командование флот штаб штаб западный западный западный западный западный западный западный западный военный военный военный военный военный военный военный военный вооружённый вооружённый вооружённый сила сила сила сила сила сила быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть революция революция революция революция революция революция февральский февральский октябрьский октябрьский октябрьский октябрьский октябрьский октябрьский ход ход ход ход отечественный отечественный отечественный отечественный война война война война война война война война война война блокада блокада блокада блокада блокада блокада блокада результат результат результат результат результат результат результат результат результат результат результат результат миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек погибнуть погибнуть погибнуть погибнуть объявить герой герой герой герой состояние состояние состояние состояние состояние состояние состояние состояние состояние состав состав состав состав состав состав состав состав воинский воинский слава кронштадт кронштадт кронштадт колпино колпино колпино чело чело северный северный северный северный северный северный северный северный северный северный северный северный северный северный северный мир мир мир мир мир мир мир мир мир мир миллионник полностью полностью полностью полностью полностью полностью европа европа европа европа европа европа европа европа европа европа европа европа житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель инновационный сценарий стратегия стратегия развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие предполагать что что что что что что что что что что составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской агломерация агломерация площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь расширение расширение москва москва москва москва москва москва москва москва москва москва москва второе второе второе важный важный важный важный важный важный важный важный экономический экономический экономический экономический экономический экономический экономический экономический экономический экономический научный научный научный научный научный научный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный транспортный транспортный транспортный транспортный транспортный транспортный транспортный узел узел узел узел исторический исторический исторический исторический исторический исторический исторический исторический связанный связанный связанный связанный связанный связанный комплекс комплекс комплекс комплекс комплекс комплекс памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник входить входить список список список список список объект объект объект объект объект объект объект объект объект объект всемирный всемирный всемирный наследие наследие наследие наследие наследие наследие наследие наследие юнеско юнеско юнеско туризм туризм туризм наиболее наиболее наиболее наиболее наиболее значимый эрмитаж эрмитаж кунсткамера кунсткамера кунсткамера мариинский мариинский мариинский мариинский мариинский театр театр театр театр театр театр театр театр театр театр театр театр театр театр национальный национальный национальный национальный национальный национальный национальный национальный библиотека библиотека библиотека библиотека библиотека русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский музей музей музей музей музей музей музей музей музей музей музей музей музей музей петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость исаакиевский исаакиевский исаакиевский исаакиевский исаакиевский исаакиевский собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект сохранение сохранение сохранение направить программа программа программа посетить посетить посетить турист турист турист турист турист турист турист предел предел приневский низменность координата занимать занимать занимать занимать занимать прилегать невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский губа губа губа губа губа губа губа губа губа многочисленный многочисленный многочисленный многочисленный остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров дельта дельта дельта дельта дельта дельта протянуться километр километр километр километр километр высота высота высота высота высота высота высота уровень уровень уровень уровень уровень уровень уровень уровень уровень уровень море море море море море район район район район район район район район район район район район район район район район север север север юг юг юг юг юг высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий место место место место место место место место место место место место место место место место место место место место место место черта черта черта черта черта дудергофский дудергофский красный красный красный село село село максимальный территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория нулевой нулевой отметка отметка система система система система система система система система отсчёт отсчёт глубина служащий служащий исходный пункт пункт нивелирный сеть сеть сеть сеть сеть сеть сеть сеть начало начало начало начало начало начало начало начало начало начало начало начало xx xx xx xx xx xx век век век век век век век век век век век век век век век век век век век век век век век век век век проходить проходить проходить проходить проходить проходить проходить обсерватория обсерватория обсерватория обсерватория меридиан использоваться использоваться качество качество качество качество качество качество географический географический географический долгота карта протяжённость протяжённость протяжённость водоток достигать водный водный водный водный водный водный водный водный водный поверхность поверхность поверхность поверхность поверхность составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять с

In [18]:
docs = [get_modality_tokens(d, MAIN_MODALITY) for d in dataset._data['vw_text']]

In [19]:
len(docs)

8603

In [20]:
docs[:3]

['год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год год петроград петроград петроград петроград петроград петроград петроград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград ленинград численность численность численность численность численность численность численность численность численность численность численность численность численность численность население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население население город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город город россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия россия . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный федеральный значение значение значение значение значение значение значение значение административный административный административный административный административный центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр центр округа округа округа ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский ленинградский область область область область область область основать основать основать основать основать царь царь царь <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> <person> являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться являться столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица столица российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский российский государство государство государство государство государство государство государство государство государство назвать назвать назвать назвать честь честь честь честь честь честь святой святой святой святой святой святой святой святой святой святой святой небесный небесный покровитель покровитель основатель основатель основатель время время время время время время время время время время время время время время время время время стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать стать большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой большой ассоциироваться имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя имя исторически культурно связать связать рождение империя империя империя империя империя империя империя вхождение современный современный современный современный современный современный современный история история история история история история история история история история история роль роль роль роль роль европейский европейский европейский великий великий великий великий великий держава расположить расположить расположить расположить расположить расположить расположить расположить расположить расположить расположить страна страна страна страна страна страна страна страна страна страна страна страна страна страна страна страна побережье побережье побережье побережье финский финский финский финский финский финский финский финский финский финский финский финский финский финский финский финский залив залив залив залив залив залив залив залив залив залив залив залив залив залив залив устье устье устье устье река река река река река река река река река река река река река река река река река река река река река нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева нева находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться находиться конституционный суд суд суд суд суд федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация федерация геральдический геральдический совет совет совет совет совет совет совет совет президент орган орган орган орган орган орган власть власть власть власть власть власть власть власть власть власть власть межпарламентский межпарламентский межпарламентский ассамблея ассамблея ассамблея снг снг разместить главный главный главный главный главный главный главный главный главный командование командование флот штаб штаб западный западный западный западный западный западный западный западный военный военный военный военный военный военный военный военный вооружённый вооружённый вооружённый сила сила сила сила сила сила быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть быть революция революция революция революция революция революция февральский февральский октябрьский октябрьский октябрьский октябрьский октябрьский октябрьский ход ход ход ход отечественный отечественный отечественный отечественный война война война война война война война война война война блокада блокада блокада блокада блокада блокада блокада результат результат результат результат результат результат результат результат результат результат результат результат миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион миллион человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек человек погибнуть погибнуть погибнуть погибнуть объявить герой герой герой герой состояние состояние состояние состояние состояние состояние состояние состояние состояние состав состав состав состав состав состав состав состав воинский воинский слава кронштадт кронштадт кронштадт колпино колпино колпино чело чело северный северный северный северный северный северный северный северный северный северный северный северный северный северный северный мир мир мир мир мир мир мир мир мир мир миллионник полностью полностью полностью полностью полностью полностью европа европа европа европа европа европа европа европа европа европа европа европа житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель житель инновационный сценарий стратегия стратегия развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие развитие предполагать что что что что что что что что что что составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить составить городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской городской агломерация агломерация площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь площадь расширение расширение москва москва москва москва москва москва москва москва москва москва москва второе второе второе важный важный важный важный важный важный важный важный экономический экономический экономический экономический экономический экономический экономический экономический экономический экономический научный научный научный научный научный научный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный культурный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный крупный транспортный транспортный транспортный транспортный транспортный транспортный транспортный узел узел узел узел исторический исторический исторический исторический исторический исторический исторический исторический связанный связанный связанный связанный связанный связанный комплекс комплекс комплекс комплекс комплекс комплекс памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник памятник входить входить список список список список список объект объект объект объект объект объект объект объект объект объект всемирный всемирный всемирный наследие наследие наследие наследие наследие наследие наследие наследие юнеско юнеско юнеско туризм туризм туризм наиболее наиболее наиболее наиболее наиболее значимый эрмитаж эрмитаж кунсткамера кунсткамера кунсткамера мариинский мариинский мариинский мариинский мариинский театр театр театр театр театр театр театр театр театр театр театр театр театр театр национальный национальный национальный национальный национальный национальный национальный национальный библиотека библиотека библиотека библиотека библиотека русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский русский музей музей музей музей музей музей музей музей музей музей музей музей музей музей петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский петропавловский крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость крепость исаакиевский исаакиевский исаакиевский исаакиевский исаакиевский исаакиевский собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор собор проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект проспект сохранение сохранение сохранение направить программа программа программа посетить посетить посетить турист турист турист турист турист турист турист предел предел приневский низменность координата занимать занимать занимать занимать занимать прилегать невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский невский губа губа губа губа губа губа губа губа губа многочисленный многочисленный многочисленный многочисленный остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров остров дельта дельта дельта дельта дельта дельта протянуться километр километр километр километр километр высота высота высота высота высота высота высота уровень уровень уровень уровень уровень уровень уровень уровень уровень уровень море море море море море район район район район район район район район район район район район район район район район север север север юг юг юг юг юг высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий высокий место место место место место место место место место место место место место место место место место место место место место место черта черта черта черта черта дудергофский дудергофский красный красный красный село село село максимальный территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория территория нулевой нулевой отметка отметка система система система система система система система система отсчёт отсчёт глубина служащий служащий исходный пункт пункт нивелирный сеть сеть сеть сеть сеть сеть сеть сеть начало начало начало начало начало начало начало начало начало начало начало начало xx xx xx xx xx xx век век век век век век век век век век век век век век век век век век век век век век век век век век проходить проходить проходить проходить проходить проходить проходить обсерватория обсерватория обсерватория обсерватория меридиан использоваться использоваться качество качество качество качество качество качество географический географический географический долгота карта протяжённость протяжённость протяжённость водоток достигать водный водный водный водный водный водный водный водный водный поверхность поверхность поверхность поверхность поверхность составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять составлять 

In [21]:
NUM_TOP_WORDS = 20

In [22]:
import torch
import transformers
import os

import json
import numpy as np

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

from torch import bfloat16
import transformers

# set quantization configuration to load large model with less GPU memory
# this requires the `bitsandbytes` library

bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,  # 4-bit quantization
    bnb_4bit_quant_type='nf4',  # Normalized float 4
    bnb_4bit_use_double_quant=True,  # Second quantization after the first
    bnb_4bit_compute_dtype=bfloat16  # Computation type
)

model_path = '/data_mil/shared/CompressaAI/deploy/models/models/openchat_openchat-3.5-1210'
tokenizer = transformers.AutoTokenizer.from_pretrained(model_path)

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_path,
    trust_remote_code=True,
    quantization_config=bnb_config,
    device_map='auto',
)
model.eval()

generator = transformers.pipeline(
    model=model, tokenizer=tokenizer,
    task='text-generation',
    temperature=0.1,
    max_new_tokens=256,
    repetition_penalty=1.1
)

prompt = "Could you explain to me how 4-bit quantization works as if I am 5?"
res = generator(prompt)
print(res[0]["generated_text"])

# System prompt describes information given to all conversations
system_prompt = """
<s>[INST] <<SYS>>
You are a helpful, respectful and honest assistant for labeling topics.
<</SYS>>
"""

# Example prompt demonstrating the output we are looking for
example_prompt = """
I have a topic that contains the following documents:
- Traditional diets in most cultures were primarily plant-based with a little meat on top, but with the rise of industrial style meat production and factory farming, meat has become a staple food.
- Meat, but especially beef, is the word food in terms of emissions.
- Eating meat doesn't make you a bad person, not eating meat doesn't make you a good one.

The topic is described by the following keywords: 'meat, beef, eat, eating, emissions, steak, food, health, processed, chicken'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.

[/INST] Environmental impacts of eating meat
"""

# Our main prompt with documents ([DOCUMENTS]) and keywords ([KEYWORDS]) tags
main_prompt = """
[INST]
I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: '[KEYWORDS]'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.
[/INST]
"""

"""<s>You are a friendly chatbot who always responds in the style of a pirate<|end_of_turn|>GPT4 Correct User: Hello, my name is<|end_of_turn|>GPT4 Correct Assistant: Charlie<|end_of_turn|>GPT4 Correct User: How are you, Charlie?<|end_of_turn|>GPT4 Correct Assistant: 
"""

# System prompt describes information given to all conversations
system_prompt = """<s>You are a helpful, respectful and honest assistant for labeling topics.<|end_of_turn|>"""

# Example prompt demonstrating the output we are looking for
example_prompt = """GPT4 Correct User: I have a topic that contains the following documents:
- Traditional diets in most cultures were primarily plant-based with a little meat on top, but with the rise of industrial style meat production and factory farming, meat has become a staple food.
- Meat, but especially beef, is the word food in terms of emissions.
- Eating meat doesn't make you a bad person, not eating meat doesn't make you a good one.

The topic is described by the following keywords: 'meat, beef, eat, eating, emissions, steak, food, health, processed, chicken'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.<|end_of_turn|>GPT4 Correct Assistant: Environmental impacts of eating meat<|end_of_turn|>"""

# Our main prompt with documents ([DOCUMENTS]) and keywords ([KEYWORDS]) tags
main_prompt = """GPT4 Correct User: I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: '[KEYWORDS]'.

Based on the information about the topic above, please create a short label of this topic. Make sure you to only return the label and nothing more.<|end_of_turn|>GPT4 Correct Assistant: """

prompt = system_prompt + example_prompt + main_prompt

prompt

In [23]:
def get_phi(topic_model):
    mtw = topic_model.c_tf_idf_.todense()
    # ptw = np.array(mtw[1:, :])
    ptw = np.array(mtw[0:, :])
    pwt = ptw.T
    vocabulary = topic_model.vectorizer_model.get_feature_names_out()

    assert pwt.shape[0] == len(vocabulary)

    # topic_names = [f'topic_{i}' for i in range(pwt.shape[1])]
    # topic_names = ['background_1'] + [f'topic_{i}' for i in range(NUM_TOPICS)]
    topic_names = ['background_1'] + [f'topic_{i}' for i in range(pwt.shape[1] - 1)]

    phi = pd.DataFrame(
        index=vocabulary,
        columns=topic_names,
        data=pwt,
    )

    return phi


def get_top_words(topic_model):
    mtw = topic_model.c_tf_idf_.todense()
    ptw = np.array(mtw[0:, :])
    pwt = ptw.T

    # topic_names = ['background_1'] + [f'topic_{i}' for i in range(NUM_TOPICS)]

    # TODO: lost topic in top words, "background -> False", because does not have -1 topic for GoodRuWiki
    topic_names = ['background_1'] + [f'topic_{i}' for i in range(pwt.shape[1] - 1)]
    topic_top_words = {
        n: topic_model.get_topic(t)
        for t, n in zip([-1] + list(range(NUM_TOPICS)), topic_names)
    }

    return topic_top_words


def get_dataset(topic_model, dataset, docs):
    cleaned_docs = topic_model._preprocess_text(docs)
    vectorizer = topic_model.vectorizer_model
    tokenizer = vectorizer.build_tokenizer()
    doc_tokens = [tokenizer(doc) for doc in cleaned_docs]
    doc_texts = [
        d + f' |{MAIN_MODALITY} ' + ' '.join(t)
        for d, t in zip(dataset._data.index, doc_tokens)
    ]
    data = [[d, t] for d, t in zip(dataset._data.index, doc_texts)]

    new_dataset = pd.DataFrame(
        columns=['id', 'vw_text'],
        data=data,
    )

    return new_dataset

In [24]:
NUM_TOPICS = 20
NUM_TOP_WORDS = 20
NUM_TRAINS = 20
STOP_WORDS = stopwords.words('russian')
LANGUAGE = -1  # 'multilingual'

In [25]:
! ls ../results

20newsgroups  mkb10  postnauka	rtlwikiperson  ruwikigood

In [26]:
SAVE_FOLDER = os.path.join('/data_mil/shared/CompressaAI/BERTopic', 'results', 'ruwikigood')

In [27]:
! mkdir -p $SAVE_FOLDER

In [28]:
SAVE_FOLDER

'/data_mil/shared/CompressaAI/BERTopic/results/ruwikigood'

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

embedding_model = TfidfVectorizer(min_df=5, max_df=int(len(docs) * 0.5), stop_words=STOP_WORDS)
embeddings = embedding_model.fit_transform(docs)
# topic_model = BERTopic().fit(docs, embeddings)

In [30]:
len(docs)

8603

In [31]:
embeddings.shape

(8603, 61682)

In [ ]:
embeddings = TfidfVectorizer(stop_words=STOP_WORDS).fit_transform(docs)

In [50]:
embeddings.shape

(8603, 264925)

In [38]:
for seed in [100]:  # range(NUM_TRAINS):
    print(seed)

    seed_save_folder = os.path.join(SAVE_FOLDER, str(seed))

    if os.path.isdir(seed_save_folder):
        contents = os.listdir(seed_save_folder)

        assert len(contents) == 3

        continue

    # TODO: os.makedirs(seed_save_folder)

    keybert = KeyBERTInspired(top_n_words=NUM_TOP_WORDS)
    mmr = MaximalMarginalRelevance(diversity=0.3, top_n_words=NUM_TOP_WORDS)
    
    representation_model = {
        "KeyBERT": keybert,
        "MMR": mmr,
    }

    umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=seed)
    vectorizer_model = CountVectorizer(stop_words=STOP_WORDS)

    topic_model = BERTopic(
        language=LANGUAGE,
        top_n_words=NUM_TOP_WORDS,

        calculate_probabilities=True,
        verbose=True,

        # embedding_model=embedding_model,          # Step 1 - Extract embeddings
        umap_model=umap_model,                    # Step 2 - Reduce dimensionality
        # hdbscan_model=hdbscan_model,            # Step 3 - Cluster reduced embeddings
        vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
                                                  # Step 5 - Extract topic words
        # representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
    )
        
    topics, probs = topic_model.fit_transform(docs, embeddings=embeddings)
    orig_num_topics = len(set(topic_model.topics_))
    doc_embeddings = topic_model.umap_model.embedding_

    hdbscan_model = HDBSCAN_flat(doc_embeddings, n_clusters=NUM_TOPICS)
    
    topic_model = BERTopic(
        language=LANGUAGE,
        top_n_words=NUM_TOP_WORDS,
        calculate_probabilities=True,
        verbose=True,
    
        umap_model=umap_model,                    # Step 2 - Reduce dimensionality
        hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
        vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
        # representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
    )

    topics, probs = topic_model.fit_transform(docs, embeddings=embeddings)
    
    new_num_topics = len(set(topic_model.topics_))
    
    # assert new_num_topics < orig_num_topics
    if new_num_topics >= orig_num_topics:
        print(f'No less topics: {new_num_topics} >= {orig_num_topics}.')

    # assert new_num_topics == NUM_TOPICS + 
    if new_num_topics != NUM_TOPICS + 1:
        print(f'WTF: failed to produce exact number of topics: {new_num_topics} != {NUM_TOPICS + 1}.')

        # whatever
        # assert abs(new_num_topics - (NUM_TOPICS + 1)) <= 2

    assert topic_model.c_tf_idf_.shape[0] == new_num_topics
    
    phi = get_phi(topic_model)
    top_words = get_top_words(topic_model)
    new_dataset = get_dataset(topic_model, dataset, docs)

    # TODO assert Falsse
    
    phi.to_csv(f'{seed_save_folder}/phi.csv')
    
    with open(f'{seed_save_folder}/top_words.json', 'w') as f:
        f.write(
            json.dumps(
                top_words, indent=4, ensure_ascii=False
            )
        )
    
    new_dataset.to_csv(f'{seed_save_folder}/dataset.csv')

    del topic_model, phi, new_dataset

2024-03-30 17:26:23,604 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

100

2024-03-30 17:27:59,448 - BERTopic - Dimensionality - Completed ✓
2024-03-30 17:27:59,450 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 17:28:07,560 - BERTopic - Cluster - Completed ✓
2024-03-30 17:28:07,566 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 17:28:30,947 - BERTopic - Representation - Completed ✓
2024-03-30 17:28:43,893 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-30 17:30:19,544 - BERTopic - Dimensionality - Completed ✓
2024-03-30 17:30:19,546 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 17:30:42,024 - BERTopic - Cluster - Completed ✓
2024-03-30 17:30:42,028 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 17:31:04,683 - BERTopic - Representation - Completed ✓

WTF: failed to produce exact number of topics: 17 != 21.

NameError: name 'Fale' is not defined

In [46]:
set(topics)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}

In [48]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,5450,0_person_год_время_стать,"[person, год, время, стать, город, человек, ча...",[<person> <person> <person> <person> <person> ...
1,1,706,1_вид_клетка_мочь_птица,"[вид, клетка, мочь, птица, акула, являться, pe...",[насекомое насекомое насекомое насекомое насек...
2,2,525,2_person_консул_год_рим,"[person, консул, год, рим, цезарь, римский, кв...",[<person> <person> <person> <person> <person> ...
3,3,411,3_матч_команда_person_сезон,"[матч, команда, person, сезон, клуб, год, чемп...",[<person> <person> <person> <person> <person> ...
4,4,392,4_альбом_группа_песня_person,"[альбом, группа, песня, person, песнь, год, му...",[beatles beatles beatles beatles beatles beatl...
5,5,308,5_картина_художник_person_год,"[картина, художник, person, год, полотно, порт...",[<person> <person> <person> <person> <person> ...
6,6,286,6_корабль_крейсер_мм_флот,"[корабль, крейсер, мм, флот, орудие, год, pers...",[линейный линейный линейный линейный линейный ...
7,7,101,7_монета_марка_денежный_год,"[монета, марка, денежный, год, монетный, номин...",[торговый торговый торговый торговый торговый ...
8,8,92,8_станция_паровоз_поезд_вагон,"[станция, паровоз, поезд, вагон, линия, год, д...",[александровский александровский александровск...
9,9,73,9_sonic_игра_hedgehog_соника,"[sonic, игра, hedgehog, соника, уровень, персо...",[sonic sonic sonic sonic sonic sonic sonic son...
10,10,60,10_восхождение_вершина_альпинист_person,"[восхождение, вершина, альпинист, person, эксп...",[<person> <person> <person> <person> <person> ...
11,11,45,11_герб_геральдический_щит_город,"[герб, геральдический, щит, город, муниципальн...",[герб герб герб герб герб герб герб герб герб ...
12,12,44,12_алфавит_письменность_буква_язык,"[алфавит, письменность, буква, язык, кириллица...",[курдский курдский курдский курдский курдский ...
13,13,40,13_фотография_фотограф_киноплёнка_person,"[фотография, фотограф, киноплёнка, person, год...",[спиритический спиритический спиритический спи...
14,14,34,14_собака_порода_бульдог_лошадь,"[собака, порода, бульдог, лошадь, шерсть, крыс...",[английский английский английский английский а...
15,15,22,15_малдёр_эпизод_агент_person,"[малдёр, эпизод, агент, person, сериал, тумс, ...",[сущность сущность сущность сущность сущность ...
16,16,14,16_покемон_игра_pokemon_nintendo,"[покемон, игра, pokemon, nintendo, игрок, пика...",[pokemon pokemon pokemon pokemon pokemon pokem...

In [47]:
probs

array([[4.33703841e-004, 4.12765117e-004, 3.04115154e-004, ...,
        3.11624880e-004, 2.73035668e-004, 4.79422263e-004],
       [8.52105858e-004, 8.04528964e-004, 6.21072604e-004, ...,
        6.48838103e-004, 5.49378073e-004, 9.41348441e-004],
       [2.51743835e-004, 2.27136198e-004, 2.32856088e-004, ...,
        2.27431234e-004, 1.90792924e-004, 2.74033365e-004],
       ...,
       [5.36562846e-004, 4.98457130e-004, 4.98985329e-004, ...,
        4.36115598e-004, 4.19582198e-004, 5.97808717e-004],
       [4.16437041e-004, 3.83560639e-004, 3.05152769e-004, ...,
        2.74464943e-004, 2.63524561e-004, 4.69710815e-004],
       [7.97832361e-308, 7.51012599e-308, 7.57606958e-308, ...,
        7.48443426e-308, 7.04970891e-308, 8.58309278e-308]])

In [39]:
phi = get_phi(topic_model)
top_words = get_top_words(topic_model)
new_dataset = get_dataset(topic_model, dataset, docs)

In [40]:
phi.head()

,background_1,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_10,topic_11,topic_12,topic_13,topic_14,topic_15
aa,0.000021,0.000066,0.0,0.00000,0.000016,0.0,0.000019,0.0,0.0,0.0,0.0,0.0,0.007627,0.0,0.0,0.0,0.0
aaa,0.000011,0.000011,0.0,0.00003,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
aaaaa,0.000003,0.000000,0.0,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
aaaaabbbbbabbbaabbababbaaababaab,0.000003,0.000000,0.0,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
aaaab,0.000004,0.000000,0.0,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [41]:
phi.columns

Index(['background_1', 'topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4',
       'topic_5', 'topic_6', 'topic_7', 'topic_8', 'topic_9', 'topic_10',
       'topic_11', 'topic_12', 'topic_13', 'topic_14', 'topic_15'],
      dtype='object')

In [42]:
top_words

{'background_1': False,
 'topic_0': [('person', 0.042461024327904114),
  ('год', 0.028026665769274293),
  ('время', 0.012182631252993337),
  ('стать', 0.010203728015430421),
  ('город', 0.008503057248634838),
  ('человек', 0.008454315951511773),
  ('часть', 0.007892679519769156),
  ('имя', 0.007234802031268627),
  ('мочь', 0.007187300486495405),
  ('являться', 0.007061139441013748),
  ('работа', 0.007048734715160412),
  ('век', 0.006955706259198057),
  ('получить', 0.006824536172941751),
  ('иметь', 0.006543076987295329),
  ('игра', 0.006439551874001519),
  ('большой', 0.006359507365025279),
  ('армия', 0.006238640861521342),
  ('война', 0.006006533723150852),
  ('фильм', 0.005999963673066351),
  ('новый', 0.005694016832708471)],
 'topic_1': [('вид', 0.03034024096957983),
  ('клетка', 0.025942453308010077),
  ('мочь', 0.02211897797194643),
  ('птица', 0.020593829955137824),
  ('акула', 0.016642959693217083),
  ('являться', 0.01444510116705008),
  ('person', 0.014318273721880692),
  ('ген', 0.013458509542084315),
  ('некоторый', 0.01308975912493078),
  ('растение', 0.013027088565738667),
  ('белок', 0.012423621258758278),
  ('самка', 0.01235332173541405),
  ('длина', 0.012100785336376126),
  ('иметь', 0.011895196080376078),
  ('рнк', 0.011655552246563271),
  ('белка', 0.011424141697631701),
  ('год', 0.011063171100981041),
  ('род', 0.01093073312323906),
  ('днк', 0.010790649200549807),
  ('самец', 0.010653922296880008)],
 'topic_2': [('person', 0.07957251407452037),
  ('консул', 0.0355334463923875),
  ('год', 0.03259080691478637),
  ('рим', 0.03041800723353811),
  ('цезарь', 0.028824259972112992),
  ('римский', 0.02658627912446139),
  ('квинта', 0.02529114124730475),
  ('сенат', 0.020207560387063336),
  ('война', 0.020027058824301093),
  ('сципион', 0.01823544431609519),
  ('император', 0.018202744820565827),
  ('легион', 0.017235612616329915),
  ('стать', 0.016627773073596124),
  ('армия', 0.015783102319871803),
  ('марка', 0.01456806707932995),
  ('время', 0.01432031189215089),
  ('источник', 0.014082303159352532),
  ('провинция', 0.012984881454378464),
  ('сын', 0.012571966465652399),
  ('город', 0.01081010628922308)],
 'topic_3': [('матч', 0.06209086674349397),
  ('команда', 0.05228923433860363),
  ('person', 0.05222696429156705),
  ('сезон', 0.04239159368337791),
  ('клуб', 0.038262692289914954),
  ('год', 0.038122847987716084),
  ('чемпионат', 0.03470903730464431),
  ('игра', 0.03457186798602374),
  ('игрок', 0.032061299628330514),
  ('турнир', 0.025627671457435178),
  ('стать', 0.025541455364207374),
  ('сборный', 0.02480663556838794),
  ('счёт', 0.02266787516312792),
  ('кубок', 0.02182089113342877),
  ('гол', 0.02170003254254844),
  ('лига', 0.021110837822529042),
  ('забить', 0.02089516736177899),
  ('тренер', 0.020619165160151314),
  ('победа', 0.020111876382484784),
  ('выиграть', 0.018848936956842845)],
 'topic_4': [('альбом', 0.0851842990270989),
  ('группа', 0.0565353578688082),
  ('песня', 0.045381946764670014),
  ('person', 0.039104247004507556),
  ('песнь', 0.028137273052958312),
  ('год', 0.0274751451558248),
  ('музыкант', 0.02698542983237595),
  ('запись', 0.022639353005622396),
  ('сингл', 0.02196121941490663),
  ('композиция', 0.021735435243773978),
  ('концерт', 0.020668147013169012),
  ('музыкальный', 0.02055424078855699),
  ('музыка', 0.01714985309457723),
  ('выпустить', 0.01712914871414145),
  ('стать', 0.016662930378172652),
  ('пластинка', 0.01571356787083496),
  ('записать', 0.015604575149359316),
  ('время', 0.015550174436116245),
  ('коллектив', 0.013479266702970899),
  ('хороший', 0.013468179247396656)],
 'topic_5': [('картина', 0.0679491782195588),
  ('художник', 0.056629846194796205),
  ('person', 0.050622609200770816),
  ('год', 0.03047436962782489),
  ('полотно', 0.023056499736460987),
  ('портрет', 0.021785304883537766),
  ('работа', 0.02005139469730156),
  ('выставка', 0.019098425024282887),
  ('искусство', 0.01673404389227091),
  ('время', 0.014432065910378324),
  ('живопись', 0.014200483593146233),
  ('музей', 0.01390538982942565),
  ('изобразить', 0.013755352389630176),
  ('искусствовед', 0.013064319513454409),
  ('фигура', 0.013004174696217024),
  ('художественный', 0.01274373494303791),
  ('галерея', 0.011767749805044206),
  ('писать', 0.01130879121012011),
  ('изображение', 0.010772797002448762),
  ('шахматы', 0.010637943805050091)],
 'topic_6': [('корабль', 0.0611544288734175),
  ('крейсер', 0.04966785537595734),
  ('мм', 0.04278304001847032),
  ('флот', 0.030314979707889315),
  ('орудие', 0.02884766013492113),
  ('год', 0.028133686010292314),
  ('person', 0.025687920130486368),
  ('линкор', 0.024148591944054314),
  ('тип', 0.023413280300600747),
  ('палуба', 0.02005727385381254),
  ('башня', 0.019972631533242982),
  ('снаряд', 0.019604626248914528),
  ('проект', 0.017967136810788376),
  ('линейный', 0.017725752208825697),
  ('установка', 0.017023731457189058),
  ('подводный', 0.01640181656884642),
  ('борт', 0.016244529707198415),
  ('лодка', 0.015524614543643225),
  ('эскадра', 0.015489102374794629),
  ('скорость', 0.014944375144341535)],
 'topic_7': [('монета', 0.13102461670596205),
  ('марка', 0.05527350719318298),
  ('денежный', 0.044651499221450716),
  ('год', 0.0406400288460294),
  ('монетный', 0.038288193596470586),
  ('номинал', 0.03523090183577946),
  ('почтовый', 0.03397873348077506),
  ('выпуск', 0.030189452053069256),
  ('единица', 0.023882815427326926),
  ('золотой', 0.0235640917641855),
  ('валюта', 0.023180314520491872),
  ('чеканка', 0.0227592300545934),
  ('серебро', 0.022408453335369966),
  ('person', 0.02223502448603913),
  ('обращение', 0.02175397887465787),
  ('серебряный', 0.020405295395997197),
  ('государство', 0.020092526589930982),
  ('талер', 0.020001628970194557),
  ('банкнот', 0.019989793160032108),
  ('чеканить', 0.019163473460090032)],
 'topic_8': [('станция', 0.09070228056027052),
  ('паровоз', 0.057463597082372135),
  ('поезд', 0.05243121451100262),
  ('вагон', 0.04795415520950858),
  ('линия', 0.04316955657984731),
  ('год', 0.03662251193924165),
  ('дорога', 0.03645706319721112),
  ('железный', 0.029773927022751515),
  ('строительство', 0.021860063694295058),
  ('депо', 0.021505315895903737),
  ('метрополитен', 0.02132301396191208),
  ('метро', 0.020482757512706472),
  ('вестибюль', 0.02041321018985964),
  ('трамвайный', 0.020147027017749453),
  ('завод', 0.018952879700772387),
  ('участок', 0.018875213388015292),
  ('троллейбус', 0.01854420436627993),
  ('московский', 0.018262261691368856),
  ('дизель', 0.017940015938626864),
  ('состав', 0.016328647866087613)],
 'topic_9': [('sonic', 0.17224179961986724),
  ('игра', 0.09250357884223097),
  ('hedgehog', 0.062336305907061705),
  ('соника', 0.05144687581579275),
  ('уровень', 0.04379958930968486),
  ('персонаж', 0.04328221924932132),
  ('sega', 0.03696724448877664),
  ('игрок', 0.03614787996833785),
  ('серия', 0.0334399505798377),
  ('ёж', 0.030774407410768773),
  ('игровой', 0.029981579029404206),
  ('adventure', 0.026562938105981516),
  ('изумруд', 0.02527885110402573),
  ('консоль', 0.024706191513924336),
  ('person', 0.023514575900293433),
  ('кольцо', 0.02265654193954611),
  ('версия', 0.022046541272303464),
  ('прохождение', 0.019906168261542755),
  ('робот', 0.019274077825312413),
  ('платформер', 0.019186521912468522)],
 'topic_10': [('восхождение', 0.09835509321268983),
  ('вершина', 0.09443499313490723),
  ('альпинист', 0.05898964334427),
  ('person', 0.05560242281780657),
  ('экспедиция', 0.05439580450044355),
  ('маршрут', 0.04381594204467094),
  ('год', 0.0379661684644394),
  ('лагерь', 0.03630885690256339),
  ('гора', 0.03545106954236432),
  ('высота', 0.03222700177304327),
  ('гребень', 0.03003509949629296),
  ('пик', 0.029430929872557885),
  ('альпинизм', 0.02518916611319794),
  ('совершить', 0.02483105717497057),
  ('метр', 0.024422001816119702),
  ('стена', 0.021125509581772617),
  ('эверест', 0.02064871356210749),
  ('подняться', 0.018945943361475166),
  ('северный', 0.01812619625400467),
  ('ледник', 0.01706028774659437)],
 'topic_11': [('герб', 0.24820183570089585),
  ('геральдический', 0.07631569041569744),
  ('щит', 0.06631573889034159),
  ('город', 0.06529210288368949),
  ('муниципальный', 0.051536205257245074),
  ('символ', 0.05116846143743039),
  ('золотой', 0.047140746440279234),
  ('городской', 0.04266011039802172),
  ('утвердить', 0.03980780904419759),
  ('год', 0.03675045767013782),
  ('гербовый', 0.032473839552252984),
  ('символика', 0.031942232055327334),
  ('совет', 0.030477901451180123),
  ('район', 0.030115174542936024),
  ('серебряный', 0.029736390505569667),
  ('ставропольский', 0.029103543430143326),
  ('изображение', 0.02835019880776952),
  ('person', 0.02586483939817463),
  ('смоленский', 0.02523612808791054),
  ('официальный', 0.025187108455847332)],
 'topic_12': [('алфавит', 0.2559041872459918),
  ('письменность', 0.12949297302667126),
  ('буква', 0.1243270131734294),
  ('язык', 0.09294793491305166),
  ('кириллица', 0.051794533046437205),
  ('год', 0.04602755907105228),
  ('букварь', 0.038154984384602235),
  ('кириллический', 0.037887338369330094),
  ('знак', 0.037745484000844404),
  ('использоваться', 0.03652142182903645),
  ('основа', 0.03614480966087923),
  ('латиница', 0.03290414894963932),
  ('латинизировать', 0.03081056087673823),
  ('звук', 0.030796125205166683),
  ('руна', 0.028320421467826696),
  ('руно', 0.026803633938704885),
  ('арабский', 0.025817841456851686),
  ('рунический', 0.025296618193609663),
  ('латинский', 0.02290952643723039),
  ('диалект', 0.022355594451362246)],
 'topic_13': [('фотография', 0.11278443418937155),
  ('фотограф', 0.04521495790322662),
  ('киноплёнка', 0.04184742594746692),
  ('person', 0.03004166274318931),
  ('год', 0.025722740384247204),
  ('объектив', 0.024393186647813297),
  ('негатив', 0.024383619281382066),
  ('изображение', 0.0243812674157538),
  ('камера', 0.023703598633983046),
  ('съёмка', 0.022985944090789204),
  ('перфорация', 0.020595856830329353),
  ('снимка', 0.02015990101715728),
  ('печать', 0.018252934018734065),
  ('фотоаппарат', 0.01761667846886095),
  ('ребёнок', 0.0169822831981887),
  ('кадр', 0.016844675045166915),
  ('формат', 0.01681538211477827),
  ('время', 0.01651863311705497),
  ('рейландёр', 0.016020162645500224),
  ('мм', 0.014919727311941819)],
 'topic_14': [('собака', 0.13259039695014088),
  ('порода', 0.11446001033696833),
  ('бульдог', 0.058232770109577364),
  ('лошадь', 0.04876017814963018),
  ('шерсть', 0.03779323223700026),
  ('крыса', 0.03514540622236073),
  ('окрас', 0.0340053507940485),
  ('карачаевский', 0.02837532129410796),
  ('рысак', 0.02806163451768351),
  ('выставка', 0.02473127646240246),
  ('орловский', 0.0230606457137666),
  ('крафт', 0.02175822225550473),
  ('год', 0.021498080556218102),
  ('стандарт', 0.019726354243827626),
  ('person', 0.016271263312770345),
  ('мочь', 0.01611663853827465),
  ('ухо', 0.01609272993122075),
  ('сиб', 0.015871518680979517),
  ('холка', 0.015605201724463731),
  ('охота', 0.015521002002515218)],
 'topic_15': [('малдёр', 0.1386228369280603),
  ('эпизод', 0.11631993906668163),
  ('агент', 0.049090525093543905),
  ('person', 0.047593315648508897),
  ('сериал', 0.04111972980469913),
  ('тумс', 0.03786522487257441),
  ('секретный', 0.03651821212407736),
  ('картер', 0.02917647118432673),
  ('фбр', 0.027500518993828337),
  ('материал', 0.027373011451345342),
  ('серия', 0.025629757135196673),
  ('fox', 0.024077945281126726),
  ('сцена', 0.023637398476370437),
  ('съёмка', 0.021304282715615113),
  ('сценарий', 0.019872107173757463),
  ('малдрать', 0.019668540165023844),
  ('домохозяйство', 0.019580396028063024),
  ('премьера', 0.01877765221036062),
  ('сезон', 0.018749264086400926),
  ('расследовать', 0.01724706793607795)]}

In [49]:
# Wow! Where is -1 topic?..

In [44]:
topic_model.get_topic(-1)

False

In [73]:
! ls $SAVE_FOLDER

0  1  10  11  12  13  14  15  16  17  18  19  2  3  4  5  6  7	8  9

! rm -r $SAVE_FOLDER/0

! rm -r /data_mil/shared/CompressaAI/BERTopic/results/postnauka/0

In [45]:
new_num_topics

52

In [74]:
SAVE_FOLDER

'/data_mil/shared/CompressaAI/BERTopic/results/ruwikigood'

In [54]:
! ls $SAVE_FOLDER

0  1  10  11  2  3  4  5  6  7	8  9

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [35]:
! ls /data_mil/shared/CompressaAI/BERTopic/results50/rtlwikiperson/

0  1  10  11  2  3  4  5  6  7	8  9

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [48]:
! ls /data_mil/shared/CompressaAI/BERTopic/results50/rtlwikiperson/11

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

! rm -r /data_mil/shared/CompressaAI/BERTopic/results50/rtlwikiperson/11

In [33]:
keybert = KeyBERTInspired(top_n_words=NUM_TOP_WORDS)
mmr = MaximalMarginalRelevance(diversity=0.3, top_n_words=NUM_TOP_WORDS)

representation_model = {
    "KeyBERT": keybert,
    "MMR": mmr,
}

umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
vectorizer_model = CountVectorizer(stop_words=STOP_WORDS)

topic_model = BERTopic(
    language=LANGUAGE,
    top_n_words=NUM_TOP_WORDS,

    calculate_probabilities=True,
    verbose=True,

    # embedding_model=embedding_model,          # Step 1 - Extract embeddings
    umap_model=umap_model,                    # Step 2 - Reduce dimensionality
    # hdbscan_model=hdbscan_model,            # Step 3 - Cluster reduced embeddings
    vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
                                              # Step 5 - Extract topic words
    # representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)
    
topics, probs = topic_model.fit_transform(docs, embeddings=embeddings)

2024-03-30 17:21:25,071 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-03-30 17:23:18,990 - BERTopic - Dimensionality - Completed ✓
2024-03-30 17:23:18,992 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-03-30 17:23:28,561 - BERTopic - Cluster - Completed ✓
2024-03-30 17:23:28,572 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-03-30 17:23:51,066 - BERTopic - Representation - Completed ✓

In [35]:
len(set(topics))

171

In [37]:
topic_model.get_topic(1)

[('картина', 0.03225299001920325),
 ('художник', 0.029269929925598223),
 ('полотно', 0.014258702951247364),
 ('портрет', 0.012852161036762714),
 ('выставка', 0.011311901541073366),
 ('искусство', 0.00945169711855185),
 ('живопись', 0.009012511979103249),
 ('искусствовед', 0.00851818232744616),
 ('изобразить', 0.00809599584320772),
 ('работа', 0.007972387468817748),
 ('музей', 0.007765781939114305),
 ('фигура', 0.0076978975667414355),
 ('галерея', 0.0074293124118641),
 ('художественный', 0.007427091181182913),
 ('шахматы', 0.007046947817575379),
 ('person', 0.006934069498057664),
 ('шахматный', 0.006474895599185693),
 ('холст', 0.006310108934025328),
 ('изображение', 0.005870506547391321),
 ('год', 0.005650590902580173)]